name: Install and test TS 2023

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  bun-unit-tests-ts-2023:
    name: bun-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: |
          cd 2023
          bun install
      - name: Run Tests
        run: |
          cd 2023
          bun test --coverage
