name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  bun-unit-tests:
    name: bun-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        run: |
          bun install
          bun test
